name: FreeRDP Test Build

on:
  push:
    branches: [ stable-* ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "Install cross-compilation toolchain"
      #run: sudo apt update && sudo apt --reinstall install mingw-w64 libgtk-3-dev libwebkit2gtk-4.0-dev build-essential ninja-build cmake zlib1g-dev libssl-dev libcairo2-dev libfreetype6 libfreetype6-dev libfreetype-dev libfontconfig1-dev xclip
      run: sudo apt update && sudo apt install mingw-w64 ninja-build build-essential git-core debhelper cdbs dpkg-dev autotools-dev cmake pkg-config xmlto libssl-dev docbook-xsl xsltproc libxkbfile-dev libx11-dev libwayland-dev libxrandr-dev libxi-dev libxrender-dev libxext-dev libxinerama-dev libxfixes-dev libxcursor-dev libxv-dev libxdamage-dev libxtst-dev libcups2-dev libpcsclite-dev libasound2-dev libpulse-dev libjpeg-dev libgsm1-dev libusb-1.0-0-dev libudev-dev libdbus-glib-1-dev uuid-dev libxml2-dev libfaad-dev libfaac-dev libcjson-dev libpkcs11-helper1-dev
      
    - name: "Debug LS"
      run: mkdir static_libs && ls
    
    - name: "Checkout Openssl"
      run: git clone -b openssl-3.1.1 https://github.com/openssl/openssl.git
    
    - name: Cross compile OpenSSL 
      run: |
        cd openssl
        ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=${{ github.workspace }}/static_libs 
        make -j build_sw
        make -j install_sw 
#--prefix=/home/runner/work/FreeRDP/FreeRDP/openssl/build

    - name: "Debug LS 2"
      run: ls
    
    - name: "Checkout cJSON"
      run: git clone --depth 1 -b v1.7.16 https://github.com/DaveGamble/cJSON.git
    
    - name: Cross compile cJSON 
      run:  cd cJSON && 
            mkdir build && 
            cd build &&
            cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../../mingw_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CJSON_TEST=OFF -DBUILD_SHARED_AND_STATIC_LIBS=ON -DCMAKE_INSTALL_PREFIX=../cJSON-install .. &&
            sudo ninja install
            
    - name: "Checkout SDL"
      run: git clone --depth 1 -b release-2.28.1 https://github.com/libsdl-org/SDL.git
    
    - name: Cross compile SDL 
      run:  cd SDL && 
            mkdir build && 
            cd build &&
            cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../../mingw_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DSDL_TEST=OFF -DSDL_TESTS=OFF -DSDL_STATIC_PIC=ON .. &&
            sudo ninja install
            
    - name: "Checkout SDL_TTF"
      run: git clone --depth 1 --shallow-submodules --recurse-submodules -b release-2.20.2 https://github.com/libsdl-org/SDL_ttf.git
    
    - name: Cross compile SDL_TTF 
      run:  cd SDL_ttf && 
            mkdir build && 
            cd build &&
            cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../../mingw_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DSDL2TTF_HARFBUZZ=ON -DSDL2TTF_FREETYPE=ON -DSDL2TTF_VENDORED=ON -DFT_DISABLE_ZLIB=OFF -DSDL2TTF_SAMPLES=OFF -DBUILD_SHARED_LIBS=OFF .. &&
            sudo ninja install
            
    - name: "Build"
      run: mkdir build && 
           cd build && 
           cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../mingw_toolchain.cmake -DOPENSSL_LIBRARIES=/usr/local/lib64/ -DZLIB_LIBRARY=/usr/local/zlib/lib/libz.so -DZLIB_INCLUDE_DIR=/usr/local/zlib/include -DCMAKE_BUILD_TYPE=Release -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DCHANNEL_URBDRC=OFF ..
        
      #-DZLIB_LIBRARY=/usr/local/zlib/lib/libz.so -DZLIB_INCLUDE_DIR=/usr/local/zlib/include
